Return all
therealklanni/hubot-factoids pull request #8
Opened 2017-03-06 15:17 UTC by attiks

Show all defined factoids

2017-03-22 01:33 UTC, therealklanni requested changes

2017-03-22 01:33 UTC, therealklanni commented on src/factoids.coffee
> +    all = @factoids.getAll()
Rather than replacing the functionality of this command, let's add a separate (new) command.

2017-03-22 10:24 UTC, attiks commented on src/factoids.coffee
> +    all = @factoids.getAll()
Any preference for the name of the new command?

2017-03-24 22:00 UTC, therealklanni commented on src/factoids.coffee
> +    all = @factoids.getAll()
No preference, as long as it's intuitive. 👍

2017-07-20 09:35 UTC, attiks commented
Finally found to the time, renamed to *List all factoids*

2017-07-20 10:22 UTC, attiks commented
Let me know if you want some more changes, but I think it's good to go

2017-07-21 01:47 UTC, therealklanni requested changes

2017-07-21 01:47 UTC, therealklanni commented on test/factoids_test.coffee
> +  it 'responds to list all factoids', (done) ->
Looks like L160-165 needs to be reverted?

2017-07-21 10:27 UTC, attiks commented on test/factoids_test.coffee
> +  it 'responds to list all factoids', (done) ->
It's to test the behavior if there's no factoid defined

2017-07-21 23:05 UTC, therealklanni commented on test/factoids_test.coffee
> +  it 'responds to list all factoids', (done) ->
That's fine, if you want to add it, but it looks like you removed the test for the URL?

2017-07-26 18:27 UTC, therealklanni approved these changes
lgtm. Thanks for your efforts!

I will get this merged and published later today.

2017-07-31 21:55 UTC, merged

2017-07-31 22:03 UTC, therealklanni commented
Sorry for the wait! (Completely spaced it)

hubot-factoids 1.2.0 published 🎉